version: '3.8'

# Services we are going to use when running
services:
  # Database instance we need to store data
  postgres:
    image: postgres:latest
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: liber
      POSTGRES_USER: chucvv
      POSTGRES_PASSWORD: postgres
  # Backend instance that depends on database instance to start.
  backend:
    image: chucvv/libertime:latest
    container_name: liber-apis
    mem_limit: 300m
    depends_on:
      - postgres
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=private-key
    ports:
      - "80:80"