version: '3.8'

# Services we are going to use when running
services:
  # Database instance we need to store data
  postgres:
    image: postgres:latest
    restart: always
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: liber
      POSTGRES_USER: chucvv
      POSTGRES_PASSWORD: postgres

  # Redis cache
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  # Backend instance that depends on database and caching instance to start.
  backend:
    image: chucvv/libertime:latest
    restart: always
    container_name: liber-apis
    mem_limit: 300m
    depends_on:
      - postgres
      - redis
    environment:
      - ENVIRONMENT=production
      - PORT=8080
      - HASH_SECRET_KEY=${HASH_SECRET_KEY}
      - REDIS_SECRET_KEY=${REDIS_SECRET_KEY}
    ports:
      - "80:8080"