apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-primary-deployment
  labels:
    name: redis-primary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-primary
  template:
    metadata:
      labels:
        name: redis-primary
    spec:
      subdomain: primary
      containers:
        - name: redis
          image: redis:alpine
          command:
            - "redis-server"
          args:
            - "--protected-mode"
            - "no"
          ports:
            - containerPort: 6379