version: "3.8"
services:
  nats-node1:
    image: nats-streaming
    volumes:
      - ./config-1.conf:/config.conf
    command: --config /config.conf
    ports:
      - 4221:4222
  nats-node2:
    image: nats-streaming
    volumes:
      - ./config-2.conf:/config.conf
    command: --config /config.conf
    ports:
      - 4222:4222
  nats-node3:
    image: nats-streaming
    volumes:
      - ./config-3.conf:/config.conf
    command: --config /config.conf
    ports:
      - 4223:4222
networks:
  default:
    driver: bridge